# Generated by Django 5.0.6 on 2024-05-29 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.CharField(blank=True, max_length=50, verbose_name='Дата-время')),
                ('quantity_adult', models.IntegerField(blank=True, verbose_name='Количество взрослых билетов')),
                ('quantity_kids', models.IntegerField(blank=True, verbose_name='Количество детских билетов')),
                ('price', models.CharField(blank=True, max_length=50, verbose_name='Цена')),
            ],
        ),
    ]
